### ISSUE TITLE
hoe tag on every item?

### ISSUE THREAD

**Issue by PengyTheGamer** [SashaKYotoz/Unseen_World#1]
so i was just checking out this mod, and it seems like minecraft:hoe tag is applied to a lot of items it shouldn't be

**Comment by SashaKYotoz** [comment]
0_0
Will look into code for it, and fix as soon as possible

**Comment by PengyTheGamer** [comment]
https://github.com/SashaKYotoz/Unseen_World/blob/master/src/main/resources/data/minecraft/tags/items/hoes.json

seems like it was here :P

**Comment by SashaKYotoz** [comment]
It was fixed, problem occured due to my inattention to streams of items in datagen
